using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("jordanwallwork")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.c31eb68fbd80d92d651b4d5c023537e669f70f7e")]
[assembly: AssemblyTitleAttribute("Jello")]
[assembly: AssemblyProductAttribute("Jello")]
[assembly: AssemblyDescriptionAttribute("Jello is a product of jordanwallwork - https://github.com/jordanwallwork/jello.")]
[assembly: AssemblyTrademarkAttribute("Jello - jordanwallwork")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2014 jordanwallwork, - Original author or authors")]

